---
- hosts: mynodes
  remote_user: ubuntu
  become: yes
  roles:
    - role: Datadog.datadog
  vars:
    datadog_api_key: <Your API KEY>
    datadog_agent_version: 1:5.20.2-1
    datadog_checks:
      nginx:
        init_config:
        instances:
          - nginx_status_url: http://example.com/nginx_status/
            tags:
              - instance:foo
